Repository GDSC-PKNU-21-22/gdsc_pknu_front, pull requests merged in 2022-09, with the labels that each got.

#35 styles/color.js에서 중복된 색깔 정의 제거
  public/assets/logo/GDSC_Intro.svg
  src/App.jsx
  src/components/common/footer/Footer.jsx
  src/components/introduce/Introduce.jsx
  src/components/mainpage/Mainpage.jsx
  src/components/mainpage/testpage/Testpage.jsx
  src/styles/color.js
Labels: refactoring

#43 Issue #41 bug: Delete Dino in Header
  src/components/common/header/Header.jsx
  src/pages/Home.jsx
Labels: bug

#46 Issue #45 feat: Create FAQ page
  src/App.jsx
  src/components/common/header/HeaderLinkGroup.jsx
  src/components/faqpage/FaqPage.jsx
  src/components/faqpage/FaqPageText.jsx
  src/pages/Faq.jsx
Labels: feature

#50 Issue #49 feat: Delete 행사 in header but Add 홈 in header
  src/components/common/header/HeaderLinkGroup.jsx
Labels: feature

#52 Issue #51 feat: When click ESC button in introduce page, URL will red…
  src/components/introduce/Introduce.jsx
Labels: feature

#48 Issue #47 bug: Delete Testpage in Homepage
  src/components/mainpage/Mainpage.jsx
  src/components/mainpage/testpage/Testpage.jsx
Labels: bug

#54 Issue #45 docs Modify layout padding margins
  src/components/faqpage/FaqPage.jsx
Labels: documentation
